function createProject1() {
    return project = 
    {
        "micro": [
            {"position":[249,282],
            "lineId":["INkzlshHZoeJyJJDw9gV","CrSr0BWo6M5HX5qmBG0p"],
            "lineTerminalId":["d1H0LPbQJHqUKcZOhYix","mamUyWUVSx7otw8KWNxy"],
            "feature":["CAN/CAN FD Communication","SecOC","Software Update"],
            "featureType": ["control", "control", "control"],
            "featureRole": ["controller", "controller", "implementer"],
            "module": "Front Facing Camera",
            "property":["AES128","RNG","SecureBoot","SecureKeystore","SecureDebug"],
            "asset":["CAN message","Secret key","Counter","Software image","Certificate","Certificate Revocation List"],
            "assetFeatureIndex": [0, 1, 1, 2, 2, 2],
            "_id":"5ed6c60da4fbf252b84c2bb1",
            "projectId":123,
            "model":"Aurix TC2",
            "type":"micro",
            "id":"1PdDYXC2FkvTkcpMOAV1",
            "attackSurface":false,
            "nickName": "Microcontroller0",
            "__v":0},
            {"position":[256,458],
            "lineId":["CrSr0BWo6M5HX5qmBG0p"],
            "lineTerminalId":[],
            "feature":["CAN/CAN FD Communication","SecOC","Software Update"],
            "featureType": ["control", "control", "control"],
            "featureRole": ["controller", "controller", "implementer"],
            "module": "Front Facing Camera",
            "property":["AES128","RNG","SecureBoot","SecureKeystore"],
            "asset":["CAN message","Secret key","Counter","Software image","Certificate","Certificate Revocation List"],
            "assetFeatureIndex": [0, 1, 1, 2, 2, 2],
            "_id":"5ed6c60da4fbf252b84c2bb2",
            "projectId":123,
            "model":"S32K",
            "type":"micro",
            "id":"FQjlvSQ7BYecb7J74WIk",
            "attackSurface":false,
            "nickName": "Microcontroller1",
            "__v":0}],
        "controlUnit": [
            {"position":[661,273],
            "lineId":["INkzlshHZoeJyJJDw9gV","3AAu8d8bAGFZHc9RV694"],
            "lineTerminalId":["rbRcC98ahS2LOEIZH465","WWats4jPaEbv9pCsRybL"],
            "feature":["SecOC"],
            "featureType": ["control"],
            "featureRole": ["controller"],
            "module": "Connected Gateway",
            "asset":["Secret key","Counter"],
            "assetFeatureIndex": [0, 0],
            "_id":"5ed6c60da4fbf252b84c2bb3",
            "projectId":123,
            "model":"Gateway",
            "type":"controlUnit",
            "id":"Q2KnDZTCGAf8kr8qpsV3",
            "attackSurface":false,
            "nickName": "Module0",
            "__v":0},
            {"position":[654,546],
            "lineId":["3AAu8d8bAGFZHc9RV694"],
            "lineTerminalId":["7er5SkUsX3jezqdoXDn6"],
            "feature":["Software Update"],
            "featureType": ["control"],
            "featureRole": ["controller"],
            "module": "Connected Gateway",
            "asset":["Software image","Certificate","Certificate Revocation List"],
            "assetFeatureIndex": [0, 0, 0],
            "_id":"5ed6c60da4fbf252b84c2bb4",
            "projectId":123,
            "model":"Cloud",
            "type":"controlUnit",
            "id":"pXsj8cPdszEq5o2rbHm1",
            "attackSurface":false,
            "nickName": "Module1",
            "__v":0}],
        "commLine":[
            {"position":[448,314,548,314],
            "terminalId":["d1H0LPbQJHqUKcZOhYix","rbRcC98ahS2LOEIZH465"],
            "terminalComponentId":["1PdDYXC2FkvTkcpMOAV1","Q2KnDZTCGAf8kr8qpsV3"],
            "terminalComponentFeature": [[], []],
            "featureType": ["control"],
            "featureRole": ["conveyor"],
            "module": "CAN bus",
            "secureProtocol":["SecOc"],
            "secureProtocolFeatureIndex": [0],
            "appProtocol":["CAN"],
            "appProtocolFeatureIndex": [0],
            "_id":"5ed6c60da4fbf252b84c2bb5",
            "projectId":123,
            "model":"CAN",
            "type":"commLine",
            "id":"INkzlshHZoeJyJJDw9gV",
            "attackSurface":true,
            "nickName": "Line0",
            "feature": ["CAN/CAN FD Communication"],
            "asset": ["CAN message", "Traffic bandwidth"],
            "assetFeatureIndex": [0, 0],
            "__v":0},
            {"position":[378,355,478,355],
            "terminalId":["WWats4jPaEbv9pCsRybL","7er5SkUsX3jezqdoXDn6"],
            "terminalComponentId":["Q2KnDZTCGAf8kr8qpsV3","pXsj8cPdszEq5o2rbHm1"],
            "terminalComponentFeature": [[], []],
            "featureType": ["control"],
            "featureRole": ["conveyor"],
            "module": "Ethernet bus",
            "secureProtocol":["TLS 1.2"],
            "secureProtocolFeatureIndex": [0],
            "appProtocol":["Automotive Ethernet"],
            "appProtocolFeatureIndex": [0],
            "_id":"5ed6c60da4fbf252b84c2bb6",
            "projectId":123,
            "model":"Ethernet",
            "type":"commLine",
            "id":"3AAu8d8bAGFZHc9RV694",
            "attackSurface":true,
            "nickName": "Line1",
            "feature": ["Ethernet Communication"],
            "asset": ["Ethernet message", "Traffic bandwidth"],
            "assetFeatureIndex": [0, 0],
            "__v":0},
            {"position":[398,428,466,428],
            "terminalId":["mamUyWUVSx7otw8KWNxy","EqeNeKBAffX3QRNlJPg6"],
            "terminalComponentId":["1PdDYXC2FkvTkcpMOAV1","FQjlvSQ7BYecb7J74WIk"],
            "terminalComponentFeature": [[], []],
            "featureType": ["control"],
            "featureRole": ["conveyor"],
            "module": "CAN bus",
            "secureProtocol":[""],
            "secureProtocolFeatureIndex": [0],
            "appProtocol":["CAN"],
            "appProtocolFeatureIndex": [0],
            "_id":"5ed6c60da4fbf252b84c2bb7",
            "projectId":123,
            "model":"CAN",
            "type":"commLine",
            "id":"CrSr0BWo6M5HX5qmBG0p",
            "attackSurface":true,
            "nickName": "Line2",
            "feature": ["CAN/CAN FD Communication"],
            "asset": ["CAN message", "Traffic bandwidth"],
            "assetFeatureIndex": [0, 0],
            "__v":0}],
        "boundary":[
            {"position":[119,174],
            "size":[439,535],
            "property":[],
            "asset":[],
            "_id":"5ed6c60da4fbf252b84c2bb8",
            "projectId":123,
            "model":"moduleBoundary",
            "type":"boundary",
            "id":"kz3AhR7WwFI3egUtQFIJ",
            "attackSurface":false,
            "nickName": "Boundary0",
            "__v":0}]
        };
} 

module.exports.dummyProject1 = createProject1;