const mongoose = require("mongoose");

const missingFeaAdvSchema = new mongoose.Schema({
    count: Number,
    assetType: {type: String, trim: true},
    subType: {type: String, trim: true},
    transmissionMedia: {type: String, trim: true},
    baseProtocol: {type: String, trim: true},
    componentID: {type: String, trim: true},
    appProtocol: {type: [String], trim: true},
    secureProtocol: {type: [String], trim: true},
    stride: {type: String, trim: true},
}, {timestamps: true});
module.exports.missingFeaAdvSchema = missingFeaAdvSchema;

const simpleCountersSchema = new mongoose.Schema({
    counterType: String,
    generatedThreatCount: Number,
    generatedThreatCountBillion: Number,
}, {timestamps: true});
module.exports.simpleCountersSchema = simpleCountersSchema;

const threatRiskAllSchema = new mongoose.Schema({
    asset: String,
    assetType: String,
    attackFeasibility: Number,
    attackFeasibilityLevel: String,
    attackPathName: String,
    attackSurface: Boolean,
    featureRole: String,
    featureType: String,
    fromFeature: String,
    id: {type: String, index: true},
    impactS: Number,
    impactSLevel: String,
    impactF: Number,
    impactFLevel: String,
    impactO: Number,
    impactOLevel: String,
    impactP: Number,
    impactPLevel: String,
    module: String,
    nickName: String,
    riskLevel: String,
    riskScore: Number,
    securityPropertyCia: String,
    securityPropertyStride: String,
    subType: String,
    threatScenario: String,
    treatment: String,
    treatmentVal: Boolean,
    type: { type: String },
    damageScenario: String,
    reviewedDateTime: Date,
    treatmentPickedDateTime: Date,
    attackFeasibilityAfter: Number,
    attackFeasibilityLevelAfter: String,
    attackFeasibilityLevelUpdated: String,
    attackFeasibilityLevelAfterUpdated: String,
    riskScoreAfter: Number,
    riskLevelAfter: String,
    riskLevelBefore: String,
    riskLevelUpdated: String,
    riskLevelAfterUpdated: String,
    attackPathNameDes: String,
    impactFAfter: Number,
    impactSAfter: Number,
    impactOAfter: Number,
    impactPAfter: Number,
    impactFLevelAfter: String,
    impactSLevelAfter: String,
    impactOLevelAfter: String,
    impactPLevelAfter: String,
    impactFLevelAfterUpdated: String,
    impactSLevelAfterUpdated: String,
    impactOLevelAfterUpdated: String,
    impactPLevelAfterUpdated: String,
    impactFLevelUpdated: String,
    impactSLevelUpdated: String,
    impactOLevelUpdated: String,
    impactPLevelUpdated: String,
    attackFeasibilityElapsed: Number,
    attackFeasibilityExpertise: Number,
    attackFeasibilityKnowledge: Number,
    attackFeasibilityWindow: Number,
    attackFeasibilityEquipment: Number,
    attackFeasibilityElapsedRationale: String,
    attackFeasibilityExpertiseRationale: String,
    attackFeasibilityKnowledgeRationale: String,
    attackFeasibilityWindowRationale: String,
    attackFeasibilityEquipmentRationale: String,
    attackFeasibilityCVSSVector: Number,
    attackFeasibilityCVSSComplexity: Number,
    attackFeasibilityCVSSPrivilege: Number,
    attackFeasibilityCVSSUser: Number,
    attackFeasibilityCVSSVectorRationale: String,
    attackFeasibilityCVSSComplexityRationale: String,
    attackFeasibilityCVSSPrivilegeRationale: String,
    attackFeasibilityCVSSUserRationale: String,
    attackFeasibilityAttackVector: String,
    attackFeasibilityAttackVectorRationale: String,
    attackFeasibilityElapsedAfter: Number,
    attackFeasibilityExpertiseAfter: Number,
    attackFeasibilityKnowledgeAfter: Number,
    attackFeasibilityWindowAfter: Number,
    attackFeasibilityEquipmentAfter: Number,
    attackFeasibilityElapsedAfterRationale: String,
    attackFeasibilityExpertiseAfterRationale: String,
    attackFeasibilityKnowledgeAfterRationale: String,
    attackFeasibilityWindowAfterRationale: String,
    attackFeasibilityEquipmentAfterRationale: String,
    attackFeasibilityCVSSVectorAfter: Number,
    attackFeasibilityCVSSComplexityAfter: Number,
    attackFeasibilityCVSSPrivilegeAfter: Number,
    attackFeasibilityCVSSUserAfter: Number,
    attackFeasibilityCVSSVectorAfterRationale: String,
    attackFeasibilityCVSSComplexityAfterRationale: String,
    attackFeasibilityCVSSPrivilegeAfterRationale: String,
    attackFeasibilityCVSSUserAfterRationale: String,
    attackFeasibilityAttackVectorAfter: String,
    attackFeasibilityAttackVectorAfterRationale: String,
    attackFeasibilityElapsedUpdated: Number,
    attackFeasibilityExpertiseUpdated: Number,
    attackFeasibilityKnowledgeUpdated: Number,
    attackFeasibilityWindowUpdated: Number,
    attackFeasibilityEquipmentUpdated: Number,
    attackFeasibilityElapsedUpdatedRationale: String,
    attackFeasibilityExpertiseUpdatedRationale: String,
    attackFeasibilityKnowledgeUpdatedRationale: String,
    attackFeasibilityWindowUpdatedRationale: String,
    attackFeasibilityEquipmentUpdatedRationale: String,
    attackFeasibilityCVSSVectorUpdated: Number,
    attackFeasibilityCVSSComplexityUpdated: Number,
    attackFeasibilityCVSSPrivilegeUpdated: Number,
    attackFeasibilityCVSSUserUpdated: Number,
    attackFeasibilityCVSSVectorUpdatedRationale: String,
    attackFeasibilityCVSSComplexityUpdatedRationale: String,
    attackFeasibilityCVSSPrivilegeUpdatedRationale: String,
    attackFeasibilityCVSSUserUpdatedRationale: String,
    attackFeasibilityAttackVectorUpdated: String,
    attackFeasibilityAttackVectorUpdatedRationale: String,
    attackFeasibilityElapsedAfterUpdated: Number,
    attackFeasibilityExpertiseAfterUpdated: Number,
    attackFeasibilityKnowledgeAfterUpdated: Number,
    attackFeasibilityWindowAfterUpdated: Number,
    attackFeasibilityEquipmentAfterUpdated: Number,
    attackFeasibilityElapsedAfterUpdatedRationale: String,
    attackFeasibilityExpertiseAfterUpdatedRationale: String,
    attackFeasibilityKnowledgeAfterUpdatedRationale: String,
    attackFeasibilityWindowAfterUpdatedRationale: String,
    attackFeasibilityEquipmentAfterUpdatedRationale: String,
    attackFeasibilityCVSSVectorAfterUpdated: Number,
    attackFeasibilityCVSSComplexityAfterUpdated: Number,
    attackFeasibilityCVSSPrivilegeAfterUpdated: Number,
    attackFeasibilityCVSSUserAfterUpdated: Number,
    attackFeasibilityCVSSVectorAfterUpdatedRationale: String,
    attackFeasibilityCVSSComplexityAfterUpdatedRationale: String,
    attackFeasibilityCVSSPrivilegeAfterUpdatedRationale: String,
    attackFeasibilityCVSSUserAfterUpdatedRationale: String,
    attackFeasibilityAttackVectorAfterUpdated: String,
    attackFeasibilityAttackVectorAfterUpdatedRationale: String,
    threatSource: String, // ruleEngine, userManual, userAddedThreatLib, dataEngine
    threatRuleEngineId: String, // designator for ruleEngine generated threat
    baseProtocol: String,
    appProtocol: [String],
    secureProtocol: [String],
    transmissionMedia: String,
    attackMethod: String,
    MITM: Boolean,
    wp29AttackIndex: [String],
    assetTag: [String],
    attackSurfaceSensorInput: Boolean,
    threatFeaLibAdvId: String,
    orgHash: String,
    userHash: String, // hash(reviewedBy)
    industry: String, // automotive, medicalDevice
    supplyChain: String, // tier-1, tier-2, serviceProvider, OEM
    attackPathLength: Number, // attackPath.length
    mitreAttackIndex: { // array index in each field shall match one merge
        matrix: String, // matrix name - mitreAttackMethod property value from systemConfig
        tacticVId: [[Number]], // array inside array, in case one threat is used multiple times in a merged threat
        techniqueVId: [[Number]], // array inside array, in case one threat is used multiple times in a merged threat
        subTechniqueVId: [[Number]], // add empty array if no subTechnique
        removedAfterMerge: [Boolean], // if user chooses to remove the original threat after merge, add true; otherwise false
    },
    newToThreatFeaAll: Boolean, // flag for threatFeaAll processing
}, {timestamps: true});
module.exports.threatRiskAllSchema = threatRiskAllSchema;

const threatFeaAllSchema = new mongoose.Schema({
    id: {type: String, index: true},
    assetType_dataInTransit: {type: Number, default: 0},
    assetType_dataAtRest: {type: Number, default: 0},
    assetType_process: {type: Number, default: 0},
    assetType_computingResource: {type: Number, default: 0},
    assetType_memoryResource: {type: Number, default: 0},
    assetType_bandwidth: {type: Number, default: 0},
    subType_generalData: {type: Number, default: 0},
    subType_code: {type: Number, default: 0},
    subType_configData: {type: Number, default: 0},
    subType_securityData: {type: Number, default: 0},
    subType_log: {type: Number, default: 0},
    attackPath_length: {type: Number, default: 0},
    attackSurfaceSensorInput: {type: Number, default: 0},
    securityPropertyCia_c: {type: Number, default: 0},
    securityPropertyCia_i: {type: Number, default: 0},
    securityPropertyCia_a: {type: Number, default: 0},
    securityPropertyStride_s: {type: Number, default: 0},
    securityPropertyStride_t: {type: Number, default: 0},
    securityPropertyStride_r: {type: Number, default: 0},
    securityPropertyStride_i: {type: Number, default: 0},
    securityPropertyStride_d: {type: Number, default: 0},
    securityPropertyStride_e: {type: Number, default: 0},
    transmissionMedia_physicalWire: {type: Number, default: 0},
    transmissionMedia_shortWireless: {type: Number, default: 0},
    transmissionMedia_longWireless: {type: Number, default: 0},
    baseProtocol_CANFD: {type: Number, default: 0}, // remove space
    baseProtocol_Ethernet: {type: Number, default: 0},
    baseProtocol_CAN: {type: Number, default: 0},
    baseProtocol_SPIUARTI2C: {type: Number, default: 0}, // remove two `/`
    baseProtocol_LIN: {type: Number, default: 0},
    baseProtocol_USB: {type: Number, default: 0},
    baseProtocol_Cellular: {type: Number, default: 0},
    baseProtocol_GNSS: {type: Number, default: 0},
    baseProtocol_Bluetooth: {type: Number, default: 0},
    baseProtocol_BluetoothLE: {type: Number, default: 0}, // remove space
    baseProtocol_WiFi: {type: Number, default: 0},
    baseProtocol_JTAG: {type: Number, default: 0},
    baseProtocol_LVDS: {type: Number, default: 0},
    baseProtocol_DSI: {type: Number, default: 0},
    baseProtocol_OpticalCameraMachineVision: {type: Number, default: 0}, // remove spaces
    baseProtocol_OpticalCameraHumanVision: {type: Number, default: 0}, // remove spaces
    baseProtocol_RADAR: {type: Number, default: 0},
    baseProtocol_LiDAR: {type: Number, default: 0},
    baseProtocol_80211p: {type: Number, default: 0}, // remove `.`
    appProtocol_HTTP: {type: Number, default: 0},
    appProtocol_FTP: {type: Number, default: 0},
    appProtocol_UDS: {type: Number, default: 0},
    appProtocol_MQTT: {type: Number, default: 0},
    appProtocol_IP: {type: Number, default: 0},
    appProtocol_DoIP: {type: Number, default: 0},
    appProtocol_SOMEIP: {type: Number, default: 0}, // remove `/`
    appProtocol_DHCP: {type: Number, default: 0},
    appProtocol_ICMP: {type: Number, default: 0},
    appProtocol_ARP: {type: Number, default: 0},
    appProtocol_AVB: {type: Number, default: 0},
    appProtocol_SMTP: {type: Number, default: 0},
    appProtocol_SNMP: {type: Number, default: 0},
    appProtocol_DNS: {type: Number, default: 0},
    securityProtocol_TLS11orearlier: {type: Number, default: 0}, // remove `.` and spaces
    securityProtocol_TLS12: {type: Number, default: 0}, // remove `.` and space
    securityProtocol_TLS13: {type: Number, default: 0}, // remove `.` and space
    securityProtocol_IPSec: {type: Number, default: 0}, 
    securityProtocol_SecOC: {type: Number, default: 0}, 
    securityProtocol_WEP: {type: Number, default: 0}, 
    securityProtocol_WPA: {type: Number, default: 0}, 
    securityProtocol_WPA2: {type: Number, default: 0}, // remove space
    securityProtocol_SSH: {type: Number, default: 0}, 
    attackFeasibilityElapsed: {type: Number, default: 0},
    attackFeasibilityExpertise: {type: Number, default: 0},
    attackFeasibilityKnowledge: {type: Number, default: 0},
    attackFeasibilityWindow: {type: Number, default: 0},
    attackFeasibilityEquipment: {type: Number, default: 0},
    riskLevel: {type: Number, default: 0},
}, {timestamps: true});
module.exports.threatFeaAllSchema = threatFeaAllSchema;